site_name: Billing Business Process
repo_url: https://github.com/Digital-Business-Council/eInvoicing
pages:
    - 'The eInvoicing Implementation Guide': 
         - 'Disclaimer': 'disclaimer.md'
         - 'Audience': 'index.md'
         - 'Introduction': 'introduction.md'
         - 'Conformance': 'conformance.md '
         - 'Distribution Pacakage': 'distributionpackage.md'
         - 'Terms and Definitions': 'termsanddefinitions.md'
         - 'Controlled Vocabulary': 'controlledvocabulary.md'
         - 'Business Processes': 'businessprocesses.md'
         - 'eInvoicing Profile': 'eInvoicingProfiles.md'
         - 'Use of Identifiers': 'useofidentifiers.md'
         - 'Identfying Services for the Interoperability Framework': 'Services-fo- the-Interoperability-Framework.md'
         - 'Validation Artefacts': 'ValidationArtefacts.md'
         - 'Support Material': 'support-artefacts.md'
         - 'Extensions to the Core Invoice - Use Cases': 'extensiontocoreservice.md'
         - 'ANNEX A - Examples of Extensions': 'annexA.md'
         - 'ANNEX B - Common Business Scenarios': 'annexB.md'
         - 'References': 'references.md'
     - 'The eInvoicing Semantic Model': 
         - 'Disclaimer': 'disclaimer.md'
         - 'Audience': 'index.md'
         - 'Introduction': 'introduction.md'
         - 'Scope': 'scope.md'
         - 'Conformance': 'conformance.md '
         - 'The Core Invoice Concept': 'coreinvoiceconcept.md'
         - 'Terms and Definitions (Normative)': 'termsanddefinitions.md'
         - 'Controlled Vocabulary (Normative)': 'controlledvocabulary.md'
         - 'Business Processes': 'businessprocesses.md'
         - 'The eInvoicing Semantic Model (Normative)': 'eInvoicingSemanticModel.md'
         - 'ANNEX A - Common Business Scenarios': 'AnnexA.md'
         - 'ANNEX B - eInvoicing Semantic Model in a Tabular Format': 'AnnexB.md'
         - 'References': 'references.md'
 theme: mkdocs
